/*
 * Star Wars API (SWAPI)
 * API documentation for SWAPI
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StarWarsApiSwapi);
  }
}(this, function(expect, StarWarsApiSwapi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StarWarsApiSwapi.DefaultApi();
  });

  describe('(package)', function() {
    describe('DefaultApi', function() {
      describe('apiCharactersIdFilmsGet', function() {
        it('should call apiCharactersIdFilmsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiCharactersIdFilmsGet call
          /*

          instance.apiCharactersIdFilmsGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiFilmsIdCharactersGet', function() {
        it('should call apiFilmsIdCharactersGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiFilmsIdCharactersGet call
          /*

          instance.apiFilmsIdCharactersGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiFilmsIdPlanetsGet', function() {
        it('should call apiFilmsIdPlanetsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiFilmsIdPlanetsGet call
          /*

          instance.apiFilmsIdPlanetsGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiFilmsIdSpeciesGet', function() {
        it('should call apiFilmsIdSpeciesGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiFilmsIdSpeciesGet call
          /*

          instance.apiFilmsIdSpeciesGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiFilmsIdStarshipsGet', function() {
        it('should call apiFilmsIdStarshipsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiFilmsIdStarshipsGet call
          /*

          instance.apiFilmsIdStarshipsGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiFilmsIdVehiclesGet', function() {
        it('should call apiFilmsIdVehiclesGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiFilmsIdVehiclesGet call
          /*

          instance.apiFilmsIdVehiclesGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiPlanetsIdCharactersGet', function() {
        it('should call apiPlanetsIdCharactersGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiPlanetsIdCharactersGet call
          /*

          instance.apiPlanetsIdCharactersGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiPlanetsIdFilmsGet', function() {
        it('should call apiPlanetsIdFilmsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiPlanetsIdFilmsGet call
          /*

          instance.apiPlanetsIdFilmsGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiSpeciesIdCharactersGet', function() {
        it('should call apiSpeciesIdCharactersGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiSpeciesIdCharactersGet call
          /*

          instance.apiSpeciesIdCharactersGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiStarshipsIdCharactersGet', function() {
        it('should call apiStarshipsIdCharactersGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiStarshipsIdCharactersGet call
          /*

          instance.apiStarshipsIdCharactersGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
