name: Push_To_ACR_And_Deploy_To_Azure_WebApp
on: 
  push:
    paths-ignore:
      - 'README.md'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        # Setup Node.js environment
        - name: 'Setup Node.js'
          uses: actions/setup-node@v3
          with:
            node-version: '18'
            cache: 'npm'
            cache-dependency-path: app/swapi/package-lock.json
        
        # Build React app
        - name: 'Install React app dependencies'
          run: |
            cd app/swapi
            npm ci
        
        - name: 'Inject commit SHA into React app source files'
          run: |
            cd app/swapi
            # Inject commit SHA into index.html and App.js
            sed -i "s/PLACEHOLDER_COMMIT_SHA/${{ github.sha }}/g" public/index.html
            sed -i "s/PLACEHOLDER_COMMIT_SHA/${{ github.sha }}/g" src/App.js
        
        - name: 'Build React app'
          run: |
            cd app/swapi
            npm run build
        
        - name: 'Copy React build to server folder'
          run: |
            cp -r app/swapi/build server/nlq-build
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/swapi:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/swapi:${{ github.sha }}

        - uses: azure/webapps-deploy@v2
          with:
            app-name: 'swapi2'
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            images: 'swapi.azurecr.io/swapi:${{ github.sha }}'

        # - name: 'Deploy to Azure Container Instances'
        #   uses: 'azure/aci-deploy@v1'
        #   with:
        #     resource-group: ${{ secrets.RESOURCE_GROUP }}
        #     dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
        #     image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
        #     registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        #     registry-username: ${{ secrets.REGISTRY_USERNAME }}
        #     registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        #     name: aci-sampleapp
        #     location: 'west us'